# Generated by Django 4.1.1 on 2022-09-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_downloadroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsync',
            name='images',
            field=models.FileField(upload_to='output/'),
        ),
    ]
