# Generated by Django 4.1.1 on 2022-09-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_uploadsync_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadRoute',
        ),
        migrations.AlterField(
            model_name='uploadsync',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
